name: solidariandev

services:
  db:
    image: postgres:18.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
      POSTGRES_DB: solidariandb
    secrets:
      - db_pass
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d solidariandb']
      interval: 5s
      timeout: 5s
      retries: 5

  db-test:
    image: postgres:18.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
      POSTGRES_DB: test
    secrets:
      - db_pass
    ports:
      - 5433:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d test']
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.12.3-alpine
    command: '-js -m 8222'
    volumes:
      - nats_data:/data
    ports:
      - 4222:4222
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8222/varz']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4.0-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      retries: 5

volumes:
  db_data:
  nats_data:

secrets:
  db_pass:
    file: ./secrets/core_password.txt
