services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP=gateway
    ports:
      - '3010:3010'
    environment:
      - CORE_URL=http://core:3000
      - CORS_ORIGIN=http://localhost:3080
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - JWT_EXPIRATION=1d
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=http://localhost:3010/auth/google/callback
      - FRONTEND_URL=http://localhost:3080
    secrets:
      - jwt_secret
    depends_on:
      - core

  core:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP=core
    environment:
      - DB_HOST=db_core
      - DB_USER=core_user
      - DB_PASSWORD_FILE=/run/secrets/db_pass_core
      - DB_NAME=core_db
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
      - STRIPE_SK=${STRIPE_SK}
      - STRIPE_PAYMENT_SUCCESS_URL=${STRIPE_PAYMENT_SUCCESS_URL}
    secrets:
      - db_pass_core
    depends_on:
      db_core:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy

  admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP=admin
    ports:
      - '3001:3001'
    environment:
      - DB_HOST=db_admin
      - DB_USER=admin_user
      - DB_PASSWORD_FILE=/run/secrets/db_pass_admin
      - DB_NAME=admin_db
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
      - SESSION_SECRET_FILE=/run/secrets/admin_session_secret
    secrets:
      - db_pass_admin
      - admin_session_secret
    depends_on:
      db_admin:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy

  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - '3080:3080'
    environment:
      - GATEWAY_API_INTERNAL_URL=http://gateway:3010
      - NEXT_PUBLIC_GATEWAY_API_URL=http://localhost:3010
    depends_on:
      - gateway

  db_core:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass_core
      POSTGRES_DB: core_db
    secrets:
      - db_pass_core
    volumes:
      - core_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U core_user -d core_db']
      interval: 5s
      timeout: 5s
      retries: 5

  db_admin:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass_admin
      POSTGRES_DB: admin_db
    secrets:
      - db_pass_admin
    volumes:
      - admin_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin_user -d admin_db']
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.12.3-alpine
    command: '-js -m 8222'
    volumes:
      - nats_data:/data
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8222/varz']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4.0-alpine
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      retries: 5

volumes:
  core_db_data:
  admin_db_data:
  nats_data:

secrets:
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  db_pass_core:
    file: ./secrets/core_password.txt
  db_pass_admin:
    file: ./secrets/admin_password.txt
  admin_session_secret:
    file: ./secrets/admin_session_secret.txt
